version: "3.7"
services:
  discord-bot:
    build:
      context: "."
      dockerfile: "Dockerfile"
    image: "wow-keys:latest"
    container_name: "wow-keys"
    volumes:
      - ./db:/var/opt/keys
    ports:
      - 8080:8080
