version: "3.7"
services:
  discord-bot:
    build:
      context: "."
      dockerfile: "Dockerfile"
    image: "discord-bot:latest"
    container_name: "discord-bot"
    volumes:
    - ./db:/var/opt/keys
    networks:
    - outside
    environment:
    - VIRTUAL_HOST=keys.nastye.xyz
    - LETSENCRYPT_HOST=keys.nastye.xyz

networks:
  outside:
    external: 
      name: outside