# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches:
      - master
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        cd client
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build .exe
      run: |
        cd client
        pyinstaller --exclude-module _bootlocale --onefile --noconsole post-savedinstances.py
    - name: Create release archive
      run: |
        cd client
        zip -r wow-keys-client-${{ env.GITHUB_REF_NAME }}.zip windows config.txt dist/post-savedinstances.exe
